name: manas
description: Voice-guided navigation app for visually impaired users
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Network
  http: ^1.2.2
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3
  path_provider: ^2.1.3
  
  # Camera & Image Processing
  camera: ^0.11.0
  image: ^4.1.7
  
  # Text-to-Speech
  flutter_tts: ^4.0.2
  
  # Speech-to-Text (for next phase)
  speech_to_text: ^6.6.0
  
  # State Management
  provider: ^6.1.1
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true